export const routes = {
  default: "*",
  login: "/",
  dashboard: "/dashboard",
  forgotPassword: "/forgetpassword",
  resetPassword: "/resetpassword",
  emailVerification: "/verify-email/:id",
  forgotResetPassword: "/forgot-reset-password/:id",
  registrationForm: "/registration-form",
  driverpageAll: "/drivers",
  createNewDriver: "/driver-detail",
  loadpageAll: "/loads",
  createNewLoad: "/load-detail",  vendorsAll: "/partners/vendors",
  createNewVendor: "/partners/vendor-detail",
  customersAll: "/partners/customers",
  createNewCustomer: "/partners/customer-detail",
  
 driverPayRoll: "/driver-payrolls",
  createNewDriverPayRoll: "/driver-payroll-detail",  billingPage: "/accounts/billing",
  createNewBillingPage: "/createnewbillingpage",
  vendorBalance: "/accounts/vendorbalance",
  fuelPage: "/fuel/fuel-cards",
  createNewFuelPage: "/fuel/fuel-card-detail",
  
  fuelImport: "/fuel/fuel-import",
  fuelTransaction: "/fuel/fuel-transactions",
  createNewFuelTransaction: "/createnewfueltransaction",
  trucks: "/equipments/trucks",
  createNewTruck: "/equipments/truck-detail",
  trailers: "/equipments/trailers",
  createNewTailers: "/equipments/trailer-detail",
  additions: "/accounts/additions",
  createNewAdditions: "/createnewadditions",
  scheduledPage: "/accounts/scheduledpage",
  createNewScheduledPage: "/createnewscheduledpage",
  chartOfAccounts: "/accounts/chartofaccounts",
  createNewChartOfAccounts: "/createnewchartofaccounts",
  expansesPage: "/accounts/expensespage",
  createNewExpansesPage: "/createnewexpansespage",
  createNewExpensesSchedulePage: "/createnewexpensesschedulepage",
  factoringReport: "/accounts/factoringreport",
  createNewFactoringReport: "/createnewfactoringreport",
  paymentsPage: "/accounts/paymentspage",
  createNewPaymentsPage: "/createnewpaymentspage",
  driverPaymentsPage: "/reports/driverpaymentspage",
  expensesReportPage: "/reports/expensesreportpage",
  grossProfitLoadPage: "/reports/grossprofitloadpage",
  grossProfitReportPage: "/reports/grossprofitreportpage",
  profitLossReportPage: "/reports/profitlossreportpage",
  rateMileReportPage: "/reports/ratemilereportpage",
  revenueDispatcherPage: "/reports/revenuedispatcherpage",
  totalRevenuePage: "/reports/totalrevenuepage",
  dispatchedBoard: "/dispatchedboard",
  UsersPage: "/users",
  docExchange: "/docexchange",
  dataLibrary: "/datalibrary",
  reportPage: "/reportpage",
  taxRateByStatePage: "/taxratebystatepage",
  safetyPage: "/safety",
  settingPage: "/settings",
  profileForm: "/profileform",
  UsersRole: "/users/user-roles",
  userAdminRole : "/users/permissions",
  DocumentApplication: "/driverDoc",
  driverDetails: "/driverDetails",
};
